
# Permalinks
#permalink: /:title

# Setup
name: Live the moment
title: Live the moment
tagline: 'tagline'
description: 'Descubra lugares. Viva cada momento.'
url: http://livethemoment.com.br/
rss: http://livethemoment.com.br/feed.xml
baseurl: '/'
baseurl_posts_img:   '/assets/images/posts/'
baseurl_featured_img: '/assets/images/hero/'
baseurl_featured_thumbnail: '/assets/images/thumbnail/'
baseurl_javascripts: '/assets/javascripts/'
icon:                your site icon path # /assets/img/icon.png [best 300px X 300px]
disqus:              http://disqus.com/by/livethe_moment  # get it on https://disqus.com/admin/

author:
  name:           	 Thaise Martins
  url:            	 www.livethemoment.com.br
 # facebook:          username
 # twitter:           username
 # google_plus:       username
 # linkedin:          username
 # pinterest:         username

# Server
destination:      	 ./_site
exclude:          	 [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port:             	 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
